id: I9E74E680
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:06:25.264678
last_modified: 2023-02-10 00:06:25.264827
source_metadata:
  title: 'MSV 3,0: Bhikṣuṇīprātimokṣa'
  language: sa
bases:
  55B1:
    base_file: 55B1.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
